### ISSUE TITLE
issue with gaps

### ISSUE THREAD

**Issue by alvesadrian** [vain/awesome-vain#5] opened 2016-08-29 01:51 UTC
am using awesome 3.4.15 from ubuntu 14.04
just cloned your repo into ~/.config/awesome/vain
added : 
require("vain")
at top of my rc.lua
and in my ~/.config/awesome/themes/default/theme.lua
theme.useless_gap_width = "5"

but awesome is crashing after that settings

**Comment by vain** [comment] 2016-08-29 14:13
Hi,

first of all, a little disclaimer: I am no longer using awesome (nor Ubuntu). This project is marked as "discontinued". As such, I can no longer "guarantee" that any of this code works. If possible, you should update to a newer version of AwesomeWM, and have a look at the work of @copycat-killer (https://github.com/copycat-killer/lain and https://github.com/copycat-killer/vain-again).

That being said, I tried to reproduce your error in a virtual machine, but (to my own surprise) it works. Two common pitfalls:
-   What is the content of your `~/.config/awesome/vain`? It should contain `init.lua` and others. A common mistake is to do `cd ~/.config/awesome && git clone https://github...` which results in the wrong directory structure. See `README.md`.
-   `require("vain")` must be placed after the other common `require` statements.

Also: Setting `theme.useless_gap_width = "5"` doesn't do anything unless you also use the `uselessfair` layout.

Hope that helps.

**Closed as completed by vain** 2016-08-29 14:13 UTC

**Comment by lcpz** [comment] 2016-08-29 15:02
In addition to what Peter said, I want to inform you that you can get awesome 3.5+ in Ubuntu 14.04 as well. It's easy to query a web search engine and find out which PPA to use.

Also note that, in awesome git branch, `useless` gaps have been implemented since last year. I think they will be pushed to branch 3.6 in the next months.
